---
title: "Análise do experimento [FPCC1]"
author: "Dandara Sousa"
output: html_notebook
---


```{r warning=FALSE, message = FALSE, echo=FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(magick)
library(grid)

knitr::opts_chunk$set(fig.width=25, fig.height=8) 

theme_set(theme_linedraw(base_family = "Roboto Condensed 200"))
```

```{r warning=FALSE}
source(here::here("code/lib.R"))
experimento = read_projectdata()
```

```{r}
  library(broom)
  library(boot)

  theta <- function(df, i){
    df <- df[i, ]
    return(mean(df$probabilidadedoar_extremapobreza))
  }
  
  booted <- boot(data = experimento, 
                statistic = theta, 
                R = 4000)
  ci = tidy(booted, 
            conf.level = .95,
            conf.method = "bca",
            conf.int = TRUE)
```

```{r}
theta2 <- function(df, i){
    df <- df[i, ]
    return(mean(df$probabilidadedoar_escola))
  }
booted2 <- boot(data = experimento,
                  statistic = theta2,
                  R = 4000)
ci2 = tidy(booted2,
            conf.level = .95,
            conf.method = "bca",
            conf.int = TRUE)
```

```{r}
theta3 <- function(df, i){
  df <- df[i, ]
  ep <- df %>% slice(i) %>% summarise(media = mean(probabilidadedoar_extremapobreza)) %>% pull(media)
  es <- df %>% slice(i) %>% summarise(media = mean(probabilidadedoar_escola)) %>% pull(media)
  return(ep - es)
}
booted3 <- boot(data = experimento,
                  statistic = theta3,
                  R = 4000)
ci3 = tidy(booted3,
            conf.level = .95,
            conf.method = "bca",
            conf.int = TRUE)
```

```{r}
estatisticas <- data.frame(narrativa = c('Extrema Pobreza', 'Escola', 'Diferenca'),
                           statistic = c(ci$statistic, ci2$statistic, ci3$statistic),
                           bias = c(ci$bias, ci2$bias, ci3$bias),
                           std.error = c(ci$std.error, ci2$std.error, ci3$std.error),
                           conf.low = c(ci$conf.low, ci2$conf.low, ci3$conf.low),
                           conf.high = c(ci$conf.high, ci2$conf.high, ci3$conf.high))
  
write_csv(estatisticas, here::here("data/estatisticas.csv"))
estatisticas = read_csv(here::here("data/estatisticas.csv"))

```

```{r}
estatisticas %>%
  filter(narrativa != "Diferenca") %>%
  ggplot(aes(statistic +1, narrativa)) +
  geom_point(size = 2) +
  geom_errorbarh(aes(xmin = conf.low +1 , xmax = conf.high + 1), height = 0) +
  scale_x_continuous(breaks=seq(1, 7, 1), limits=c(1, 7)) + 
  theme(axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.y = element_blank(),
        panel.grid.major.x = element_blank())
ggsave("../data/tendenciaadoar.png",width=8, height=4)
```

```{r}
estatisticas %>%
  filter(narrativa == "Diferenca") %>%
  ggplot(aes(statistic +1, narrativa)) +
  geom_point(size = 2) +
  geom_errorbarh(aes(xmin = conf.low +1 , xmax = conf.high + 1), height = 0) +
  theme(axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.y = element_blank(), panel.grid.major.x = element_blank())
ggsave("../data/icdadiferenca.png",width=8, height=4)
```

```{r}
experimento %>%
  group_by(doacao) %>%
  summarise(n= n()) %>%
  ggplot(aes(y = n, x = doacao, label = n)) + geom_bar(stat = "identity") + geom_text()
```

```{r}
extremapobreza <- experimento %>%
  group_by(probabilidadedoar_extremapobreza) %>%
  summarise(n = n()) %>%
  ggplot(aes(probabilidadedoar_extremapobreza+1, n)) + geom_bar(stat = "identity") +
  scale_x_discrete(limits=1:7) +
  theme(axis.title.y = element_blank(), axis.title.x = element_blank(), panel.grid.major.x = element_blank()) +
  labs(title = " ") 
extremapobreza
```

```{r}
escola <- experimento %>%
  group_by(probabilidadedoar_escola) %>%
  summarise(n = n()) %>%
  ggplot(aes(probabilidadedoar_escola +1, n)) + geom_bar(stat = "identity") +
  scale_x_discrete(limits=1:7) +
  theme(axis.title.y = element_blank(), axis.title.x = element_blank(), panel.grid.major.x = element_blank()) +
  labs(title = " ")
escola
```

```{r}
library(ggpubr)
ggarrange(extremapobreza, escola, ncol = 1, nrow= 2)
ggsave("../data/distribuicao.png",width=8, height=4)
```

```{r}
library(extrafont)
font_import()
loadfonts()
```

